### ISSUE TITLE
app's bundle id

### ISSUE THREAD

**Issue by maplepy** [haxi0/TrollBoard#1]
Is there an easy way to get the app's bundle id ?

**Comment by binnichtaktiv** [comment]
> Is there an easy way to get the app's bundle id ?

Use this shortcut 
https://www.icloud.com/shortcuts/489a3ebff784423394079d22b0f66d96

**Comment by oyeanu** [comment]
> Is there an easy way to get the app's bundle id ? 

http://com.apple.facetime@2x
http://com.apple.mobiletimer@2x
http://com.apple.Maps@2x
http://com.apple.reminders@2x
http://com.apple.AppStore@2x
http://com.apple.Preferences@2x
http://com.apple.Music@2x
http://com.apple.mobilesafari@2x
http://com.google.ios.youtube@2x
http://com.google.ios.ytcreator@2x
com.exile90.icleanerpro@2x
com.saurik.Cydia@2x
com.reddit.Reddit@2x
http://com.apple.MobileSMS@2x
com.burbn.instagram@2x
http://com.apple.camera@2x
http://com.apple.mobilenotes@2x
http://com.apple.mobilecal@2x
com.atebits.Tweetie2@2x
http://com.apple.mobilephone@2x
http://com.apple.mobilemail@2x
net.whatsapp.WhatsAppSMB@2x
net.whatsapp.WhatsApp@2x
http://com.apple.mobileslideshow@2x
http://com.apple.weather@2x
com.tigisoftware.Filza@2x
ph.telegra.Telegraph@2x
com.getdropbox.Dropbox@2x
http://com.google.Drive@2x
http://com.apple.DocumentsApp@2x
ws.hbang.Terminal@2x
mediaboxhd.event.2020@2x
http://com.apple.mobileslideshow@2x
pinterest@2x
com.julioverne.cydown@2x
http://com.apple.iMovie@2x
http://com.apple.mobilegarageband@2x
http://com.apple.MobileAddressBook@2x


Just remove @2x

**Comment by maplepy** [comment]
> > Is there an easy way to get the app's bundle id ?
> 
> Use this shortcut https://www.icloud.com/shortcuts/489a3ebff784423394079d22b0f66d96

Great thanks!
